//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.ExaminationSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSchedule
    {
        public int ID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string TestName { get; set; }
        public string TimeAllowed { get; set; }
        public string NumberOfQuestions { get; set; }
        public Nullable<System.DateTime> TestStartDate { get; set; }
        public Nullable<System.DateTime> TestEndDate { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<decimal> PassMarks { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
